#!/bin/sh
# Launch the existing Worker Agent as a separate, single-task CPU process.
set -eu

if [ "$#" -ne 2 ]; then
  echo "usage: run_server_cpu_worker.sh PRIVATE_WORKER_ENV PYTHON_WITH_FROZEN_DEPS" >&2
  exit 2
fi

worker_env=$1
worker_python=$2
if [ ! -f "$worker_env" ] || [ ! -x "$worker_python" ]; then
  echo "Worker environment file or Python executable is unavailable" >&2
  exit 2
fi

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
set -a
# This owner-controlled, mode-0600 file is generated by backend_v2.workers.provision.
. "$worker_env"
set +a
: "${WORKER_ID:?}"
: "${TOKEN:?}"
: "${BACKEND_URL:?}"
: "${MODEL_HASH:?}"
: "${MODEL_VERSION:?}"
: "${EPILOCATE_FROZEN_ROOT:?}"
: "${WORKER_DATA_ROOT:?}"
export WORKER_DEVICE=CPU
export PYTHONPATH="$repo_root${PYTHONPATH:+:$PYTHONPATH}"
cd "$repo_root"
exec "$worker_python" -m worker
